# Generated by Django 5.2.12 on 2026-03-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VEG', 'Veg'), ('NONVEG', 'Non-Veg')], max_length=10, unique=True)),
            ],
        ),
    ]
