# Generated by Django 5.2.12 on 2026-03-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_sortoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortoption',
            name='is_active',
        ),
    ]
