# Generated by Django 5.2.12 on 2026-03-29 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Food Stories & Recipes', max_length=255)),
                ('subtitle', models.TextField(default='Discover delicious recipes, chef tips and food culture')),
                ('media_file', models.FileField(help_text='Upload a GIF or Video for the hero section', upload_to='blog/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Hero',
                'verbose_name_plural': 'Blog Hero',
            },
        ),
        migrations.CreateModel(
            name='FoodGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Food Gallery',
                'verbose_name_plural': 'Food Galleries',
            },
        ),
        migrations.CreateModel(
            name='TrendingFoodStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog/trending/')),
                ('preview', models.TextField(help_text='Short preview of the story')),
                ('detail', models.TextField(help_text='Full detail of the story')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trending Food Story',
                'verbose_name_plural': 'Trending Food Stories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(upload_to='blog/posts/')),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(help_text='Display date string (e.g., Oct 12, 2023)', max_length=100)),
                ('description', models.TextField(help_text='Brief description/excerpt')),
                ('detail', models.TextField(help_text='Full article content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
