# Generated by Django 5.2.12 on 2026-04-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cheftip_foodculture_healthyeating_streetfoodguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(upload_to='blog/posts/'),
        ),
        migrations.AlterField(
            model_name='cheftip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cheftip',
            name='image',
            field=models.FileField(upload_to='blog/chef_tips/'),
        ),
        migrations.AlterField(
            model_name='foodculture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodculture',
            name='image',
            field=models.FileField(upload_to='blog/culture/'),
        ),
        migrations.AlterField(
            model_name='foodgallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodgallery',
            name='image',
            field=models.FileField(upload_to='blog/gallery/'),
        ),
        migrations.AlterField(
            model_name='healthyeating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='healthyeating',
            name='image',
            field=models.FileField(upload_to='blog/healthy/'),
        ),
        migrations.AlterField(
            model_name='streetfoodguide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='streetfoodguide',
            name='image',
            field=models.FileField(upload_to='blog/street_guides/'),
        ),
        migrations.AlterField(
            model_name='trendingfoodstory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trendingfoodstory',
            name='image',
            field=models.FileField(upload_to='blog/trending/'),
        ),
    ]
