# Generated by Django 5.2.12 on 2026-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji or Lucide icon name', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
